# Generated by Django 3.1.4 on 2022-01-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklead',
            name='form_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
