# Generated by Django 3.1.4 on 2022-01-30 02:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_facebooklead_form_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.IntegerField()),
                ('form_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='facebooklead',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='facebooklead',
            name='form_name',
        ),
        migrations.AddField(
            model_name='facebooklead',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facebooklead',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook.adform'),
        ),
    ]
