# Generated by Django 3.1.4 on 2022-03-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_auto_20220130_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adform',
            name='form_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
