# Generated by Django 3.1.4 on 2022-03-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_facebooklead_to_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooklead',
            name='to_reply',
            field=models.BooleanField(default=True),
        ),
    ]
