# Generated by Django 3.1.4 on 2022-04-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_auto_20220328_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebooklead',
            old_name='form',
            new_name='contact',
        ),
    ]
