# Generated by Django 3.1.4 on 2022-04-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0007_auto_20220407_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklead',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facebooklead',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
