# Generated by Django 3.1.4 on 2022-04-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0009_auto_20220416_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklead',
            name='is_unsubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
