# Generated by Django 3.1.4 on 2022-05-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0011_auto_20220524_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='adform',
            name='bulk_accepted',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adform',
            name='bulk_tried',
            field=models.IntegerField(null=True),
        ),
    ]
