# Generated by Django 3.1.4 on 2022-05-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0012_auto_20220524_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adform',
            name='bulk_accepted',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='adform',
            name='bulk_tried',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
