# Generated by Django 3.1.4 on 2022-05-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0014_facebooklead_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooklead',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
