# Generated by Django 3.1.4 on 2022-06-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0015_auto_20220527_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklead',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
