# Generated by Django 3.1.4 on 2022-05-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0071_remove_like_is_liked'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_url', models.CharField(max_length=250)),
                ('shortened_url', models.CharField(max_length=250)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
            ],
        ),
    ]
