# Generated by Django 3.1.4 on 2022-05-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hash',
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='hash_code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
