# Generated by Django 3.1.4 on 2023-01-04 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('pineapple_user', models.CharField(blank=True, max_length=100, null=True)),
                ('pineapple_password', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('sid', models.CharField(blank=True, max_length=150, null=True)),
                ('token', models.CharField(blank=True, max_length=150, null=True)),
                ('tel_api', models.CharField(blank=True, max_length=150, null=True)),
                ('vonage_api_key', models.CharField(blank=True, max_length=150, null=True)),
                ('vonage_api_secret', models.CharField(blank=True, max_length=150, null=True)),
                ('signal_api_token', models.CharField(blank=True, max_length=150, null=True)),
                ('signal_space_url', models.CharField(blank=True, max_length=150, null=True)),
                ('signal_project_id', models.CharField(blank=True, max_length=150, null=True)),
                ('plivo_id', models.CharField(blank=True, max_length=150, null=True)),
                ('plivo_token', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_permitted', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_lead', models.BooleanField(default=False)),
                ('is_response', models.BooleanField(default=False)),
                ('is_link', models.BooleanField(default=False)),
                ('is_bulk', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_undelivered', models.BooleanField(default=False)),
                ('is_ani', models.BooleanField(default=False)),
                ('is_campaign', models.BooleanField(default=False)),
                ('is_export', models.BooleanField(default=False)),
                ('is_subadmin', models.BooleanField(default=False)),
                ('is_dnis', models.BooleanField(default=False)),
                ('is_gateway', models.BooleanField(default=False)),
                ('is_limit', models.BooleanField(default=False)),
                ('is_delete_lead', models.BooleanField(blank=True, default=False, null=True)),
                ('file_attached', models.BooleanField(default=False)),
                ('balance', models.FloatField(default=0.0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Ani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('ani', models.CharField(blank=True, max_length=20, null=True)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.admin')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.addgateway')),
            ],
        ),
        migrations.CreateModel(
            name='Autoresponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('response', models.TextField()),
                ('gif_url', models.CharField(max_length=250, null=True)),
                ('delay_days', models.IntegerField(default=0)),
                ('delay_mins', models.IntegerField(default=0)),
                ('delay_hours', models.IntegerField(default=0)),
                ('is_sat', models.BooleanField(default=False)),
                ('is_sun', models.BooleanField(default=False)),
                ('is_mon', models.BooleanField(default=False)),
                ('is_tue', models.BooleanField(default=False)),
                ('is_wed', models.BooleanField(default=False)),
                ('is_thu', models.BooleanField(default=False)),
                ('is_fri', models.BooleanField(default=False)),
                ('everyday', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_time', models.TimeField(null=True)),
                ('last_time', models.TimeField(null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('ani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.ani')),
            ],
        ),
        migrations.CreateModel(
            name='BulkSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gif_url', models.CharField(blank=True, max_length=250, null=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.ani')),
            ],
        ),
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sequence', models.BooleanField(default=False)),
                ('is_bulk', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Css',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cam_grey', models.BooleanField(default=True)),
                ('is_back_img', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='default')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
                ('view', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('mms_price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
            ],
        ),
        migrations.CreateModel(
            name='InOutSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fax', 'fax'), ('sms', 'sms')], default='sms', max_length=15)),
                ('dnis', models.CharField(blank=True, max_length=20, null=True)),
                ('gif_url', models.CharField(blank=True, max_length=500, null=True)),
                ('sent', models.TextField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('dlr', models.TextField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('del_status', models.CharField(default=None, max_length=12, null=True)),
                ('error', models.CharField(default=None, max_length=200, null=True)),
                ('dlr_details', models.TextField(blank=True, null=True)),
                ('code', models.CharField(default=None, max_length=5, null=True)),
                ('order', models.IntegerField(default=1)),
                ('undel_count', models.IntegerField(default=0)),
                ('alter_link_count', models.IntegerField(default=0)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('is_mms', models.BooleanField(default=False)),
                ('is_manual', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('is_lead', models.BooleanField(default=False)),
                ('to_reply', models.BooleanField(default=False)),
                ('is_wait', models.BooleanField(default=False)),
                ('is_bulk', models.BooleanField(default=False)),
                ('is_incoming', models.BooleanField(default=False)),
                ('has_incoming', models.BooleanField(default=False)),
                ('check_keyword', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reply_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('ani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.ani')),
                ('autoresponse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.autoresponse')),
                ('bulk_sms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.bulksms')),
                ('gateway', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.gateway')),
                ('image', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.image')),
            ],
        ),
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam', models.CharField(help_text="spam shouldn't be more than 20 chracters", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ani', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('dnis', models.CharField(blank=True, max_length=20, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_sms', models.BooleanField(default=False)),
                ('new_leads', models.BooleanField(default=False)),
                ('check_keyword', models.BooleanField(default=False)),
                ('is_bulk', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.day')),
            ],
        ),
        migrations.CreateModel(
            name='UserPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuickResponseTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
            ],
        ),
        migrations.CreateModel(
            name='QuickResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.quickresponsetitle')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ani', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='responder.ani')),
            ],
        ),
        migrations.CreateModel(
            name='NumberUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('thread', models.IntegerField()),
                ('message', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='mms/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogicResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('reply', models.TextField()),
                ('gif_url', models.CharField(blank=True, max_length=250, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('ani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.ani')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.image')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('sms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.inoutsms')),
            ],
        ),
        migrations.CreateModel(
            name='Dlr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ani', models.CharField(blank=True, max_length=20, null=True)),
                ('dnis', models.CharField(blank=True, max_length=20, null=True)),
                ('result_code', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('msg_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='unknown', max_length=15)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
            ],
        ),
        migrations.AddField(
            model_name='bulksms',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.image'),
        ),
        migrations.AddField(
            model_name='autoresponse',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.image'),
        ),
        migrations.CreateModel(
            name='AssignedAni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('ani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.ani')),
            ],
        ),
        migrations.CreateModel(
            name='AssignContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
            ],
        ),
        migrations.AddField(
            model_name='addgateway',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.admin'),
        ),
        migrations.AddField(
            model_name='addgateway',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.gateway'),
        ),
    ]
