# Generated by Django 3.1.4 on 2022-03-07 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebook', '0003_auto_20220130_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('pineapple_user', models.CharField(blank=True, max_length=100, null=True)),
                ('pineapple_password', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('sid', models.CharField(blank=True, max_length=150, null=True)),
                ('token', models.CharField(blank=True, max_length=150, null=True)),
                ('tel_api', models.CharField(blank=True, max_length=150, null=True)),
                ('vonage_api_key', models.CharField(blank=True, max_length=150, null=True)),
                ('vonage_api_secret', models.CharField(blank=True, max_length=150, null=True)),
                ('signal_api_token', models.CharField(blank=True, max_length=150, null=True)),
                ('signal_space_url', models.CharField(blank=True, max_length=150, null=True)),
                ('signal_project_id', models.CharField(blank=True, max_length=150, null=True)),
                ('plivo_id', models.CharField(blank=True, max_length=150, null=True)),
                ('plivo_token', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_permitted', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_lead', models.BooleanField(default=False)),
                ('is_response', models.BooleanField(default=False)),
                ('is_link', models.BooleanField(default=False)),
                ('is_bulk', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_undelivered', models.BooleanField(default=False)),
                ('is_ani', models.BooleanField(default=False)),
                ('is_campaign', models.BooleanField(default=False)),
                ('is_export', models.BooleanField(default=False)),
                ('is_subadmin', models.BooleanField(default=False)),
                ('is_dnis', models.BooleanField(default=False)),
                ('is_gateway', models.BooleanField(default=False)),
                ('is_limit', models.BooleanField(default=False)),
                ('is_delete_lead', models.BooleanField(blank=True, default=False, null=True)),
                ('file_attached', models.BooleanField(default=False)),
                ('balance', models.FloatField(default=0.0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Ani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ani', models.CharField(blank=True, max_length=20, null=True)),
                ('balance', models.FloatField(default=0.0)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(default=None, upload_to='lead/')),
                ('hidden', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Css',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cam_grey', models.BooleanField(default=True)),
                ('is_back_img', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
                ('view', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('mms_price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='MaxSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_max_try', models.IntegerField(default=0)),
                ('followup_max_try', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(blank=True, default=0, max_length=30, null=True)),
                ('charge', models.IntegerField(blank=True, default=0, null=True)),
                ('max_lead', models.IntegerField(blank=True, default=0, null=True)),
                ('max_sequence', models.IntegerField(blank=True, default=0, null=True)),
                ('max_followup', models.IntegerField(blank=True, default=0, null=True)),
                ('max_logic', models.IntegerField(blank=True, default=0, null=True)),
                ('max_ppl', models.IntegerField(blank=True, default=0, null=True)),
                ('max_pps', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PplLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppl_link', models.CharField(blank=True, max_length=150, null=True)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='PpsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pps_link', models.CharField(blank=True, max_length=200, null=True)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam', models.CharField(help_text="spam shouldn't be more than 20 chracters", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ani', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('dnis', models.CharField(blank=True, max_length=20, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.day')),
            ],
        ),
        migrations.CreateModel(
            name='UserPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_access', models.BooleanField(default=False)),
                ('is_user_panel', models.BooleanField(default=False)),
                ('is_create_user', models.BooleanField(default=False)),
                ('is_support', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('subadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(help_text='sequence should start from 1')),
                ('message', models.TextField(blank=True, help_text="{Cooll|wellll|Alrightt|(Sound)-cool|Oky|Great\t|Wwell|All right|ohh-oky|Cool|Okay|Okay cool|cool|ok cool}I'm just getting over a breakup {?|??|???|????} <<link>>", null=True)),
                ('delay', models.IntegerField(blank=True, default=0, null=True)),
                ('is_logic', models.BooleanField(blank=True, default=None, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('campaign', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.campaign')),
                ('image', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.image')),
                ('ppl_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.ppllink')),
                ('pps_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.ppslink')),
            ],
        ),
        migrations.CreateModel(
            name='NumberUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField()),
                ('thread', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.campaign')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.adform')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogicResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('reply', models.TextField()),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('campaign', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='InOutSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnis', models.CharField(blank=True, max_length=20, null=True)),
                ('sent', models.TextField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=150, null=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('del_status', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('error', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('dlr_details', models.TextField(blank=True, null=True)),
                ('code', models.IntegerField(default=0)),
                ('followup_order', models.IntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('reply_count', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('unsent_count', models.IntegerField(default=0)),
                ('link_count', models.IntegerField(default=0)),
                ('mms_count', models.IntegerField(default=0)),
                ('undel_count', models.IntegerField(default=0)),
                ('alter_link_count', models.IntegerField(default=0)),
                ('is_pps', models.BooleanField(default=False)),
                ('is_ppl', models.BooleanField(default=False)),
                ('is_mms', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('is_undel', models.BooleanField(default=False)),
                ('is_lead', models.BooleanField(default=False)),
                ('is_manual', models.BooleanField(default=False)),
                ('is_followup', models.BooleanField(default=False)),
                ('to_reply', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('ani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.ani')),
                ('campaign', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.campaign')),
                ('gateway', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.gateway')),
                ('image', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.image')),
            ],
        ),
        migrations.CreateModel(
            name='FollowupSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(blank=True, default=0, null=True)),
                ('delay', models.IntegerField(blank=True, default=0, null=True)),
                ('message', models.TextField(blank=True, help_text="{Cooll|wellll|Alrightt|(Sound)-cool|Oky|Great\t|Wwell|All right|ohh-oky|Cool|Okay|Okay cool|cool|ok cool}I'm just getting over a breakup {?|??|???|????} <<link>>", null=True)),
                ('is_logic', models.BooleanField(blank=True, default=None, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('campaign', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.campaign')),
                ('image', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.image')),
                ('ppl_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.ppllink')),
                ('pps_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.ppslink')),
            ],
        ),
        migrations.CreateModel(
            name='Dlr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ani', models.CharField(blank=True, max_length=20, null=True)),
                ('dnis', models.CharField(blank=True, max_length=20, null=True)),
                ('result_code', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('msg_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='unknown', max_length=15)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='default')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
            ],
        ),
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_job', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ani',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.campaign'),
        ),
        migrations.AddField(
            model_name='ani',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.addgateway'),
        ),
        migrations.CreateModel(
            name='AlterPps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pps_link', models.CharField(max_length=250)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.campaign')),
                ('pps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.ppslink')),
            ],
        ),
        migrations.CreateModel(
            name='AlterPpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppl_link', models.CharField(max_length=250)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.campaign')),
                ('ppl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.ppllink')),
            ],
        ),
        migrations.AddField(
            model_name='addgateway',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.admin'),
        ),
        migrations.AddField(
            model_name='addgateway',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.gateway'),
        ),
    ]
