# Generated by Django 3.1.4 on 2023-01-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addgateway',
            name='tel_token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
