# Generated by Django 3.1.4 on 2022-03-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='numberupload',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='numberupload',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
