# Generated by Django 3.1.4 on 2023-01-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0002_addgateway_tel_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addgateway',
            old_name='tel_token',
            new_name='tel_connection_id',
        ),
    ]
