# Generated by Django 3.1.4 on 2022-03-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0004_auto_20220307_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberupload',
            name='schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
