# Generated by Django 3.1.4 on 2022-03-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0007_auto_20220307_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mms/'),
        ),
    ]
