# Generated by Django 3.1.4 on 2022-03-07 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0008_auto_20220307_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberupload',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='mms/'),
            preserve_default=False,
        ),
    ]
