# Generated by Django 3.1.4 on 2022-03-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0013_auto_20220307_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inoutsms',
            name='is_blocked',
        ),
    ]
