# Generated by Django 3.1.4 on 2022-03-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0014_remove_inoutsms_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutsms',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inoutsms',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
