# Generated by Django 3.1.4 on 2022-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0015_auto_20220316_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutsms',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
