# Generated by Django 3.1.4 on 2022-03-19 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0016_inoutsms_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='campaign',
        ),
    ]
