# Generated by Django 3.1.4 on 2022-03-20 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0017_remove_image_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inoutsms',
            name='link_count',
        ),
        migrations.RemoveField(
            model_name='inoutsms',
            name='mms_count',
        ),
        migrations.RemoveField(
            model_name='inoutsms',
            name='reply_count',
        ),
        migrations.RemoveField(
            model_name='inoutsms',
            name='sent_count',
        ),
        migrations.RemoveField(
            model_name='inoutsms',
            name='unsent_count',
        ),
    ]
