# Generated by Django 3.1.4 on 2022-03-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0018_auto_20220320_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutsms',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
