# Generated by Django 3.1.4 on 2022-03-25 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0019_auto_20220323_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alterpps',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='alterpps',
            name='pps',
        ),
        migrations.RemoveField(
            model_name='ppllink',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='ppllink',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='followupsms',
            name='ppl_link',
        ),
        migrations.RemoveField(
            model_name='followupsms',
            name='pps_link',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='ppl_link',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='pps_link',
        ),
        migrations.DeleteModel(
            name='AlterPpl',
        ),
        migrations.DeleteModel(
            name='AlterPps',
        ),
        migrations.DeleteModel(
            name='PplLink',
        ),
    ]
