# Generated by Django 3.1.4 on 2022-03-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0020_auto_20220325_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
            ],
        ),
    ]
