# Generated by Django 3.1.4 on 2022-03-28 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_auto_20220321_0038'),
        ('responder', '0021_quickresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.campaign')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.adform')),
            ],
        ),
    ]
