# Generated by Django 3.1.4 on 2022-03-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0022_assigncontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='delay',
            new_name='delay_days',
        ),
        migrations.AddField(
            model_name='sequence',
            name='delay_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='delay_mins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
