# Generated by Django 3.1.4 on 2022-03-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0024_auto_20220328_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutsms',
            name='gif_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
