# Generated by Django 3.1.4 on 2022-03-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0025_inoutsms_gif_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutsms',
            name='is_incoming',
            field=models.BooleanField(default=False),
        ),
    ]
