# Generated by Django 3.1.4 on 2022-04-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_auto_20220328_0256'),
        ('responder', '0026_inoutsms_is_incoming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoresponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('delay_days', models.IntegerField(default=0)),
                ('delay_mins', models.IntegerField(default=0)),
                ('delay_hours', models.IntegerField(default=0)),
                ('is_sat', models.BooleanField(default=False)),
                ('is_sun', models.BooleanField(default=False)),
                ('is_mon', models.BooleanField(default=False)),
                ('is_tue', models.BooleanField(default=False)),
                ('is_wed', models.BooleanField(default=False)),
                ('is_thu', models.BooleanField(default=False)),
                ('is_fri', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.adform')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.image')),
            ],
        ),
    ]
