# Generated by Django 3.1.4 on 2022-04-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0028_auto_20220403_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponse',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
