# Generated by Django 3.1.4 on 2022-04-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_auto_20220328_0256'),
        ('responder', '0029_autoresponse_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logicresponse',
            name='campaign',
        ),
        migrations.AddField(
            model_name='logicresponse',
            name='contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facebook.adform'),
        ),
        migrations.AlterField(
            model_name='dlr',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin'),
        ),
        migrations.AlterField(
            model_name='logicresponse',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin'),
        ),
    ]
