# Generated by Django 3.1.4 on 2022-04-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0030_auto_20220403_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
