# Generated by Django 3.1.4 on 2022-04-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_auto_20220328_0256'),
        ('responder', '0031_autoresponse_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inoutsms',
            name='campaign',
        ),
        migrations.AddField(
            model_name='inoutsms',
            name='contact',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facebook.adform'),
        ),
        migrations.AlterField(
            model_name='autoresponse',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.image'),
        ),
        migrations.AlterField(
            model_name='inoutsms',
            name='gateway',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.gateway'),
        ),
        migrations.AlterField(
            model_name='inoutsms',
            name='image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.image'),
        ),
    ]
