# Generated by Django 3.1.4 on 2022-04-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0032_auto_20220404_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inoutsms',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='inoutsms',
            name='is_followup',
        ),
        migrations.RemoveField(
            model_name='inoutsms',
            name='is_manual',
        ),
        migrations.RemoveField(
            model_name='inoutsms',
            name='is_ppl',
        ),
        migrations.RemoveField(
            model_name='inoutsms',
            name='is_pps',
        ),
    ]
