# Generated by Django 3.1.4 on 2022-04-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0033_auto_20220404_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inoutsms',
            name='is_undel',
        ),
        migrations.AddField(
            model_name='autoresponse',
            name='first_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='autoresponse',
            name='last_time',
            field=models.TimeField(null=True),
        ),
    ]
