# Generated by Django 3.1.4 on 2022-04-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0035_auto_20220406_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='followupsms',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='followupsms',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='followupsms',
            name='image',
        ),
        migrations.DeleteModel(
            name='MaxSent',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.RemoveField(
            model_name='ppslink',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='ppslink',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='image',
        ),
        migrations.RemoveField(
            model_name='assigncontact',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='defaultmessage',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='dlr',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='numberupload',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='weekend',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='FollowupSms',
        ),
        migrations.DeleteModel(
            name='PpsLink',
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
    ]
