# Generated by Django 3.1.4 on 2022-04-06 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0036_auto_20220406_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ani',
            name='contact',
        ),
    ]
