# Generated by Django 3.1.4 on 2022-04-06 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0037_remove_ani_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigncontact',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin'),
        ),
    ]
