# Generated by Django 3.1.4 on 2022-04-07 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0038_assigncontact_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigncontact',
            old_name='form',
            new_name='contact',
        ),
    ]
