# Generated by Django 3.1.4 on 2022-04-07 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0039_auto_20220407_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ani',
            name='balance',
        ),
    ]
