# Generated by Django 3.1.4 on 2022-04-07 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0040_remove_ani_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ani',
            name='admin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.admin'),
        ),
    ]
