# Generated by Django 3.1.4 on 2022-04-07 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0041_auto_20220407_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='super_admin',
        ),
        migrations.DeleteModel(
            name='SubAdmin',
        ),
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
    ]
