# Generated by Django 3.1.4 on 2022-04-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0042_auto_20220407_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutsms',
            name='check_keyword',
            field=models.BooleanField(default=False),
        ),
    ]
