# Generated by Django 3.1.4 on 2022-04-07 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0043_inoutsms_check_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicresponse',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.image'),
        ),
    ]
