# Generated by Django 3.1.4 on 2022-04-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0044_logicresponse_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberupload',
            old_name='form',
            new_name='contact',
        ),
    ]
