# Generated by Django 3.1.4 on 2022-04-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0045_auto_20220407_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponse',
            name='everyday',
            field=models.BooleanField(default=True),
        ),
    ]
