# Generated by Django 3.1.4 on 2022-04-09 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0046_autoresponse_everyday'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickResponseTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='quickresponse',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.quickresponsetitle'),
        ),
    ]
