# Generated by Django 3.1.4 on 2022-04-09 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0047_auto_20220409_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickresponsetitle',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin'),
        ),
    ]
