# Generated by Django 3.1.4 on 2022-04-12 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0007_auto_20220407_2235'),
        ('responder', '0048_quickresponsetitle_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.admin')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.adform')),
            ],
        ),
    ]
