# Generated by Django 3.1.4 on 2022-04-12 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0049_bulksms'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulksms',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.image'),
        ),
    ]
