# Generated by Django 3.1.4 on 2022-04-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0050_bulksms_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulksms',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
