# Generated by Django 3.1.4 on 2022-04-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0051_bulksms_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutsms',
            name='bulk_sms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.bulksms'),
        ),
    ]
