# Generated by Django 3.1.4 on 2022-04-13 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0052_inoutsms_bulk_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ani', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='responder.ani')),
            ],
        ),
    ]
