# Generated by Django 3.1.4 on 2022-04-15 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0054_inoutsms_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutsms',
            name='autoresponse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.autoresponse'),
        ),
    ]
