# Generated by Django 3.1.4 on 2022-04-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0056_remove_inoutsms_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ani',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
