# Generated by Django 3.1.4 on 2022-04-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0057_ani_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponse',
            name='ani',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.ani'),
        ),
    ]
