# Generated by Django 3.1.4 on 2022-04-17 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0058_autoresponse_ani'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoresponse',
            name='ani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.ani'),
        ),
    ]
