# Generated by Django 3.1.4 on 2022-04-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0059_auto_20220417_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoresponse',
            name='ani',
        ),
    ]
