# Generated by Django 3.1.4 on 2022-04-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0009_auto_20220416_0202'),
        ('responder', '0061_autoresponse_ani'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoresponse',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin'),
        ),
        migrations.AlterField(
            model_name='autoresponse',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook.adform'),
        ),
    ]
