# Generated by Django 3.1.4 on 2022-04-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0062_auto_20220417_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponse',
            name='gif_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
