# Generated by Django 3.1.4 on 2022-04-18 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0064_auto_20220418_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutsms',
            name='bulk_sms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.bulksms'),
        ),
    ]
