# Generated by Django 3.1.4 on 2022-04-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0065_auto_20220418_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicresponse',
            name='gif_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
