# Generated by Django 3.1.4 on 2022-04-21 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0066_logicresponse_gif_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicresponse',
            name='ani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.ani'),
        ),
    ]
