# Generated by Django 3.1.4 on 2022-05-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0069_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='sms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.inoutsms'),
        ),
    ]
