# Generated by Django 3.1.4 on 2022-05-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0070_like_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_liked',
        ),
    ]
