# Generated by Django 3.1.4 on 2022-05-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0071_remove_like_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponse',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
