# Generated by Django 3.1.4 on 2022-05-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0072_autoresponse_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoresponse',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
