# Generated by Django 3.1.4 on 2022-05-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0073_auto_20220527_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inoutsms',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='inoutsms',
            name='followup_order',
        ),
        migrations.AddField(
            model_name='inoutsms',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
