# Generated by Django 3.1.4 on 2022-05-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0074_auto_20220527_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutsms',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
