# Generated by Django 3.1.4 on 2022-06-01 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0075_auto_20220531_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentAutoresponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoresponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.autoresponse')),
            ],
        ),
    ]
