# Generated by Django 3.1.4 on 2022-06-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0078_auto_20220601_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentautoresponse',
            old_name='contact',
            new_name='lead',
        ),
    ]
