# Generated by Django 3.1.4 on 2022-06-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0079_auto_20220601_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoresponse',
            name='order',
        ),
    ]
