# Generated by Django 3.1.4 on 2022-06-03 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0080_remove_autoresponse_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedAni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.ani')),
            ],
        ),
    ]
