# Generated by Django 3.1.4 on 2022-06-03 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0081_assignedani'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedani',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.admin'),
        ),
    ]
