# Generated by Django 3.1.4 on 2022-06-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0083_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='is_working',
            new_name='check_keyword',
        ),
        migrations.AddField(
            model_name='worker',
            name='new_leads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='scheduled_sms',
            field=models.BooleanField(default=False),
        ),
    ]
