# Generated by Django 3.1.4 on 2022-06-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0085_inoutsms_reply_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutsms',
            name='reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
