# Generated by Django 3.1.4 on 2022-06-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0086_auto_20220611_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutsms',
            name='reply_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
