# Generated by Django 3.1.4 on 2022-06-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0087_auto_20220612_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutsms',
            name='has_incoming',
            field=models.BooleanField(default=False),
        ),
    ]
