# Generated by Django 3.1.4 on 2022-06-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0088_inoutsms_has_incoming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutsms',
            name='reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
