# Generated by Django 3.1.4 on 2022-06-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0089_auto_20220615_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutsms',
            name='reply_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
