# Generated by Django 3.1.4 on 2022-06-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0090_auto_20220615_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulksms',
            name='ani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.ani'),
        ),
    ]
