# Generated by Django 3.1.4 on 2022-06-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0091_bulksms_ani'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulksms',
            name='admin',
        ),
    ]
