# Generated by Django 3.1.4 on 2022-07-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0092_remove_bulksms_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutsms',
            name='is_bulk',
            field=models.BooleanField(default=False),
        ),
    ]
