# Generated by Django 3.1.4 on 2022-07-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0093_inoutsms_is_bulk'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutsms',
            name='is_wait',
            field=models.BooleanField(default=False),
        ),
    ]
