# Generated by Django 3.1.4 on 2022-07-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0094_inoutsms_is_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulksms',
            name='gif_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
