# Generated by Django 3.1.4 on 2022-07-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0095_bulksms_gif_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutsms',
            name='dlr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
