# Generated by Django 3.1.4 on 2022-08-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0097_auto_20220728_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentAutoresponse',
        ),
    ]
