# Generated by Django 3.1.4 on 2022-08-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0098_delete_sentautoresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_bulk',
            field=models.BooleanField(default=False),
        ),
    ]
