# Generated by Django 3.1.4 on 2022-09-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0099_worker_is_bulk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjob',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='cron_job',
        ),
        migrations.AddField(
            model_name='cronjob',
            name='is_bulk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='is_sequence',
            field=models.BooleanField(default=False),
        ),
    ]
