# Generated by Django 3.1.4 on 2022-12-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0100_auto_20220914_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutsms',
            name='type',
            field=models.CharField(choices=[('fax', 'fax'), ('sms', 'sms')], default='sms', max_length=15),
        ),
    ]
