# Generated by Django 3.1.4 on 2022-12-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0101_inoutsms_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutsms',
            name='code',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='inoutsms',
            name='del_status',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='inoutsms',
            name='error',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inoutsms',
            name='message_id',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
