# Generated by Django 3.1.4 on 2022-12-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0102_auto_20221218_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutsms',
            name='gif_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
